### ISSUE TITLE
4.2.0 on Win10 - Error querying the EVE server status

### ISSUE THREAD

**Issue by BlackRookSix** [mgoeppner/evemon#47]
Getting constant popups that EveMon cannot contact the server.  Yet, eve-offline.net and the game launcher both clearly show the game is up and running.

No firewalls running or interfering.

EVEMon.Common.Net.HttpWebClientServiceException: The server at esi.evetech.net returned an error. The full response returned by the server was: 504 (Gateway Timeout) ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 504 (Gateway Timeout).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at EVEMon.Common.Net.HttpClientServiceRequest.EnsureSuccessStatusCode(HttpResponseMessage response)
   at EVEMon.Common.Net.HttpClientServiceRequest.<SendAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at EVEMon.Common.Net.HttpClientServiceRequest.<SendAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EVEMon.Common.Net.HttpWebClientService.<DownloadStreamAsync>d__11`1.MoveNext()

**Comment by Zharkahn** [comment]
I am having the exact issue. My error text is identical to yours.
I checked my API permissions, and all looks fine there.

How is this fixed?

Thanks

**Comment by mgoeppner** [comment]
This was an issue with the ESI gateway, which can be flaky, especially around downtime.

Out of date, closing.
