### ISSUE TITLE
4.2.2 crashing when adding characters on Wine

### ISSUE THREAD

**Issue by foundObjects** [mgoeppner/evemon#61]
I'm attempting to run 4.2.2 via flatpak Wine (Bottles) and it crashes immediately when I try to add a character.

Repro:

Install Flatpak, then install the 'Bottles' flatpak.

Launch Bottles, create a new bottle and install dotnet 4.8 inside (warning this takes a while.) 

Install evemon in the bottle, then run it.

Click File > Add Character and EVEMon crashes:

```
EVEMon Version: 4.2.2.5058
.NET Runtime Version: 4.0.30319.42000
Operating System: Microsoft Windows NT 10.0.19043.0
Executable Path: "C:\Program Files (x86)\EVEMon\EVEMon.exe" 
System.Net.HttpListenerException (0x80004005): Call not implemented
   at System.Net.HttpListener.SetUrlGroupProperty(HTTP_SERVER_PROPERTY property, IntPtr info, UInt32 infosize)
   at System.Net.HttpListener.SetServerTimeout(Int32[] timeouts, UInt32 minSendBytesPerSecond)
   at System.Net.HttpListenerTimeoutManager.SetTimespanTimeout(HTTP_TIMEOUT_TYPE type, TimeSpan value)
   at EVEMon.Common.Service.SSOWebServerHttpListener..ctor()
   at EVEMon.ApiCredentialsManagement.EsiKeyUpdateOrAdditionWindow..ctor()
   at EVEMon.MainWindow.addAPIKeyMenu_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


Datafile report:
  eve-blueprints-en-US.xml.gzip (240KiB - 208afd8b80f09d614910af6506a179ca)
  eve-certificates-en-US.xml.gzip (45KiB - 540000f7c111354769a54fa31e57d411)
  eve-geography-en-US.xml.gzip (1011KiB - 5f957d390b34fe57f971a30f480ff1a6)
  eve-items-en-US.xml.gzip (4145KiB - fe7e6f529c3b6f9b401ac5f7502ed92f)
  eve-masteries-en-US.xml.gzip (21KiB - 3668b50996fc40a0c0853fec427b5712)
  eve-properties-en-US.xml.gzip (58KiB - 939d20318306c606d4fe290dfde72c06)
  eve-reprocessing-en-US.xml.gzip (113KiB - 139646f9fc2a97b76030ab5d19c76879)
  eve-skills-en-US.xml.gzip (26KiB - f56eb59ce4050cc3ad360ce08753ce4e)


Diagnostic Log:
0d 0h 00m 00s > Starting up
0d 0h 00m 00s > EveMonClient.Initialize - begin
0d 0h 00m 00s > Program.StartupAsync - done
0d 0h 00m 00s > Settings.TryDeserializeFromFile - begin
0d 0h 00m 00s > Settings.TryDeserializeFromFile - done
0d 0h 00m 00s > Settings.Import - begin
0d 0h 00m 00s > EveMonClient.OnSchedulerChanged
0d 0h 00m 00s > Settings.Import - done
0d 0h 00m 00s > EveMonClient.OnSettingsChanged
0d 0h 00m 00s > Main loop - start
0d 0h 00m 01s > MainWindow.OnLoad
0d 0h 00m 01s > TimeCheck.ScheduleCheck - in 00:00:01
0d 0h 00m 01s > UpdateManager.ScheduleCheck - in 00:00:10
0d 0h 00m 01s > Main window - loaded
0d 0h 00m 01s > Datafiles.Load - begin
0d 0h 00m 02s > TimeCheck.BeginCheckAsync
0d 0h 00m 02s > TimeCheck.OnCheckCompleted - Synchronised
0d 0h 00m 02s > TimeCheck.ScheduleCheck - in 1.00:00:00
0d 0h 00m 03s > EveMonClient.OnServerStatusUpdated
0d 0h 00m 05s > Datafiles.Load - done
0d 0h 00m 05s > Settings.ImportData - begin
0d 0h 00m 05s > EveMonClient.OnCharacterCollectionChanged
0d 0h 00m 05s > EveMonClient.OnESIKeyCollectionChanged
0d 0h 00m 05s > EveMonClient.OnMonitoredCharactersChanged
0d 0h 00m 05s > Settings.ImportData - done
0d 0h 00m 05s > EveMonClient.OnSettingsChanged
```

**Comment by nikolasbasler** [comment]
I have the same issue when running EVEMon 4.2.2 under Crossover 22.1.1 (trial version) on my MacOS 13.3.1:

EVEMon Version: 4.2.2.5058
.NET Runtime Version: 4.0.30319.42000
Operating System: Microsoft Windows NT 10.0.10240.0
Executable Path: "C:\Program Files\EVEMon\EVEMon.exe"
System.NotImplementedException: The method or operation is not implemented.
  at EVEMon.Common.Service.SSOWebServerHttpListener..ctor () [0x0006e] in <20950a592aee4cb88241d34627b81ed3>:0 
  at EVEMon.ApiCredentialsManagement.EsiKeyUpdateOrAdditionWindow..ctor () [0x00013] in <11e1de01eb1846f98bb07ebb28ab2f59>:0 
  at (wrapper remoting-invoke-with-check) EVEMon.ApiCredentialsManagement.EsiKeyUpdateOrAdditionWindow..ctor()
  at EVEMon.MainWindow.addAPIKeyMenu_Click (System.Object sender, System.EventArgs e) [0x00000] in <11e1de01eb1846f98bb07ebb28ab2f59>:0 
  at System.Windows.Forms.ToolStripItem.RaiseEvent (System.Object key, System.EventArgs e) [0x0001b] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.ToolStripItem.OnClick (System.EventArgs e) [0x00001] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.ToolStripMenuItem.OnClick (System.EventArgs e) [0x0001d] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.ToolStripItem.HandleClick (System.EventArgs e) [0x00051] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.ToolStripItem.HandleMouseUp (System.Windows.Forms.MouseEventArgs e) [0x000fd] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.ToolStripItem.FireEventInteractive (System.EventArgs e, System.Windows.Forms.ToolStripItemEventType met) [0x00053] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.ToolStripItem.FireEvent (System.EventArgs e, System.Windows.Forms.ToolStripItemEventType met) [0x00103] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.ToolStripItem.FireEvent(System.EventArgs,System.Windows.Forms.ToolStripItemEventType)
  at System.Windows.Forms.ToolStrip.OnMouseUp (System.Windows.Forms.MouseEventArgs mea) [0x0007d] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.ToolStripDropDown.OnMouseUp (System.Windows.Forms.MouseEventArgs mea) [0x00001] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.Control.WmMouseUp (System.Windows.Forms.Message& m, System.Windows.Forms.MouseButtons button, System.Int32 clicks) [0x001c3] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x005a0] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.ScrollableControl.WndProc (System.Windows.Forms.Message& m) [0x00043] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.ToolStrip.WndProc (System.Windows.Forms.Message& m) [0x00128] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.ToolStripDropDown.WndProc (System.Windows.Forms.Message& m) [0x00070] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.OnMessage (System.Windows.Forms.Message& m) [0x00001] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x000b3] in <7eb7f98ebac24936922af35e6761d8be>:0 
  at System.Windows.Forms.NativeWindow.Callback (System.Windows.Forms.Message& m) [0x00025] in <7eb7f98ebac24936922af35e6761d8be>:0 


Datafile report:
  eve-blueprints-en-US.xml.gzip (241KiB - 881582dbbf90e4ceeb68a3a92ad5fb05)
  eve-certificates-en-US.xml.gzip (45KiB - 540000f7c111354769a54fa31e57d411)
  eve-geography-en-US.xml.gzip (1012KiB - bf28397b579b77afad83da9c748d5694)
  eve-items-en-US.xml.gzip (4239KiB - 85b31b43771fb593979ef09b864e7fba)
  eve-masteries-en-US.xml.gzip (21KiB - 3668b50996fc40a0c0853fec427b5712)
  eve-properties-en-US.xml.gzip (58KiB - 63e778ccf4c7ca639f9587ca913476d8)
  eve-reprocessing-en-US.xml.gzip (113KiB - 8559d3f1a0e013f880655e4c4c4646fe)
  eve-skills-en-US.xml.gzip (26KiB - bfe90ea8fcb5ba855e872f375ea1bf2b)


Diagnostic Log:
0d 0h 00m 00s > Starting up
0d 0h 00m 01s > EveMonClient.Initialize - begin
0d 0h 00m 01s > EveMonClient.Initialize - done
0d 0h 00m 01s > Settings.Import - begin
0d 0h 00m 01s > EveMonClient.OnSchedulerChanged
0d 0h 00m 01s > Settings.Import - done
0d 0h 00m 01s > EveMonClient.OnSettingsChanged
0d 0h 00m 01s > Main loop - start
0d 0h 00m 03s > EveMonClient.Run
0d 0h 00m 03s > TimeCheck.ScheduleCheck - in 00:00:01
0d 0h 00m 04s > UpdateManager.ScheduleCheck - in 00:00:10
0d 0h 00m 04s > Main window - loaded
0d 0h 00m 04s > Datafiles.Load - begin
0d 0h 00m 05s > TimeCheck.BeginCheckAsync
0d 0h 00m 05s > TimeCheck.OnCheckCompleted - Synchronised
0d 0h 00m 05s > TimeCheck.ScheduleCheck - in 1.00:00:00

0d 0h 00m 05s > ExceptionHandler.LogException - Handled exception
    System.IO.DirectoryNotFoundException: Could not find a part of the path "C:\var\folders\xq\w685zgjx7gx_8d2c602w1vc40000gn\T\tmp2fe8e700.tmp".
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x00164] in <e70d6e9587d64cb3abb4b3f99bbf5a0d>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,bool,System.IO.FileOptions)
  at System.IO.Path.GetTempFileName () [0x00072] in <e70d6e9587d64cb3abb4b3f99bbf5a0d>:0 
  at EVEMon.Common.Controls.CustomCursors.GetCursorFromResource (System.Byte[] resource) [0x00000] in <20950a592aee4cb88241d34627b81ed3>:0 
    
0d 0h 00m 07s > EveMonClient.OnServerStatusUpdated
0d 0h 00m 15s > UpdateManager.OnCheckCompleted
0d 0h 00m 15s > UpdateManager.ScheduleCheck - in 12:00:00
0d 0h 00m 18s > Datafiles.Load - done
0d 0h 00m 18s > Settings.ImportData - begin
0d 0h 00m 18s > EveMonClient.OnCharacterCollectionChanged
0d 0h 00m 18s > EveMonClient.OnESIKeyCollectionChanged
0d 0h 00m 18s > EveMonClient.OnMonitoredCharactersChanged
0d 0h 00m 18s > Settings.ImportData - done
0d 0h 00m 18s > EveMonClient.OnSettingsChanged

0d 0h 00m 21s > ExceptionHandler.LogException - Handled exception
    System.IO.DirectoryNotFoundException: Could not find a part of the path "C:\var\folders\xq\w685zgjx7gx_8d2c602w1vc40000gn\T\tmp7bf30ff8.tmp".
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x00164] in <e70d6e9587d64cb3abb4b3f99bbf5a0d>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,bool,System.IO.FileOptions)
  at System.IO.Path.GetTempFileName () [0x00072] in <e70d6e9587d64cb3abb4b3f99bbf5a0d>:0 
  at EVEMon.Common.Helpers.FileHelper.OverwriteOrWarnTheUserAsync (System.String destFileName, System.Func`2[T,TResult] writeContentFunc) [0x0002c] in <20950a592aee4cb88241d34627b81ed3>:0 
  at EVEMon.Common.Settings.SaveImmediateAsync () [0x000ad] in <20950a592aee4cb88241d34627b81ed3>:0

**Comment by mgoeppner** [comment]
Hi,

For linux to work, you need to use a build from this branch: https://github.com/mgoeppner/evemon/pull/41

EVEMon 5.x.x may have better support on linux, due to the dotnet8 upgrade (which brings the code inline with .net standard 2.x.

OSX is completely unsupported at the moment due to the lack of a viable winforms compatibilty library.
