### ISSUE TITLE
error looking up character identities 

### ISSUE THREAD

**Issue by ArcAIN6** [mgoeppner/evemon#71]
Everytime evemon starts up, it complains "error looking up character identities"

Error seems to be some sort of 404

```EVEMon 4.2.2.5058

API Error:
Error looking up character identities.
HTTP error: A request to esi.evetech.net failed with status: 404 (Not Found).


EVEMon.Common.Net.HttpWebClientServiceException: A request to esi.evetech.net failed with status: 404 (Not Found). ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at EVEMon.Common.Net.HttpClientServiceRequest.EnsureSuccessStatusCode(HttpResponseMessage response)
   at EVEMon.Common.Net.HttpClientServiceRequest.<SendAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at EVEMon.Common.Net.HttpClientServiceRequest.<SendAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EVEMon.Common.Net.HttpWebClientService.<DownloadStreamAsync>d__11`1.MoveNext()```

**Comment by mgoeppner** [comment]
Does this error persist after clearing the cache and re-authenticating the character?

**Comment by ArcAIN6** [comment]
Yes, the issue is persistent. Clearing cache, and re-authing does not fix the issue.
