### ISSUE TITLE
Evemon throws error on system shutdown

### ISSUE THREAD

**Issue by MarkHolmstrom** [mgoeppner/evemon#83]
On shutdown the following .NET Runtime error gets logged with [5.0.0-preview-2](https://github.com/mgoeppner/evemon/releases/tag/5.0.0-preview-2)

```
Application: EVEMon.exe
CoreCLR Version: 8.0.1124.51707
.NET Version: 8.0.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.InvalidAsynchronousStateException: An error occurred invoking the method.  The destination thread no longer exists.
   at System.Windows.Forms.Control.WaitForWaitHandle(WaitHandle waitHandle)
   at System.Windows.Forms.Control.EndInvoke(IAsyncResult asyncResult)
   at EVEMon.Common.Extensions.EventHandlerExtensions.ThreadSafeInvoke(EventHandler eventHandler, Object sender, EventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

Didn't have this issue with my previous 4.2.2 install.

**Comment by evemav** [comment]
This should be fixed in the latest releases by https://github.com/mgoeppner/evemon/pull/113
